### ISSUE TITLE
[BUG] - CodeServer Git Integration cannot pull/push due to no user existing for uid 1000

### ISSUE THREAD

**Issue by dharhas** [nebari-dev/nebari#1592]
### Describe the bug

When using the CodeServer git integration, pull/push etc fail with the following error:

![image](https://user-images.githubusercontent.com/561301/206280221-683194b7-37ec-496a-a268-964b8d38392c.png)

log info

```
> git pull --tags origin main
No user exists for uid 1000
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

### Expected behavior

Using git commans (pull, push etc) within codeserver should work.

### OS and architecture in which you are running Nebari

Nebari on GCP

### How to Reproduce the problem?

- setup your git keys 
- clone a repo
- make a branch
- make a commit
- attempt to push the commit back to remote

### Compute environment

GCP

### Anything else?

git works from the command line in the terminal, I did not test the jupyter-git extension

**Comment by costrouc** [comment]
Interesting bug. Why does VS expect that the user has a username. We can get this to work if we can get the nsswrapper bits (that are running in jupyterlab worker). If we can set the following environment variables for code-server this should be fixed https://github.com/nebari-dev/nebari/blob/jupyterlab-conda-store/nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/jupyterhub/03-profiles.py#L229-L233.

**Comment by iameskild** [comment]
We will need to circle back to this and confirm that this is still an issue.
